name: Update SRI Hash

on:
  push:
    paths:
      - 'src/proj/main.js'

  workflow_dispatch:

jobs:
  update-sri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify file locations
        run: ls -R  # Check the structure to find where main.js is located

      - name: Run SRI Update Python Script
        run: python scripts/update_sri.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/proj/index.html
          git commit -m 'Update SRI hash for main.js'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
