name: Update SRI Hash

on:
  push:
    branches:
      - develop
    paths:
      - 'main.js'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-sri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Explicitly install sri-toolbox globally or locally
      - name: Install sri-toolbox globally
        run: npm install -g sri-toolbox

      - name: Generate SRI hash and update HTML
        run: |
          # Generate SRI hash using sha256
          HASH=$(sri-toolbox --algo sha256 main.js)
          
          # Update HTML file with the new integrity hash
          sed -i "s|<script src=\"main.js\".*>|<script src=\"main.js\" integrity=\"sha256-$HASH\" crossorigin=\"anonymous\"></script>|" index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Update SRI hash for main.js'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
