name: Update SRI Hash

on:
  # Trigger on any push to any branch
  push:
    paths:
      - '**/main.js'  # Run whenever main.js changes, on any branch

  # Trigger only on pull requests that target the develop branch
  pull_request:
    branches:
      - develop  # Only run the action when the PR targets the develop branch
    paths:
      - '**/main.js'  # Only run if main.js is part of the PR

  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-sri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find the main.js and index.html files
        id: find-files
        run: |
          MAIN_JS=$(find . -name "main.js")
          INDEX_HTML=$(find . -name "index.html")
          echo "MAIN_JS=$MAIN_JS" >> $GITHUB_ENV
          echo "INDEX_HTML=$INDEX_HTML" >> $GITHUB_ENV
          echo "Found main.js at: $MAIN_JS"
          echo "Found index.html at: $INDEX_HTML"

      - name: Generate SRI hash using openssl and update HTML
        run: |
          # Use the file paths from the previous step
          HASH=$(openssl dgst -sha256 -binary $MAIN_JS | openssl base64 -A)
          
          # Update HTML file with the new integrity hash
          sed -i "s|<script src=\"$MAIN_JS\".*>|<script src=\"$MAIN_JS\" integrity=\"sha256-$HASH\" crossorigin=\"anonymous\"></script>|" $INDEX_HTML

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add $INDEX_HTML
          git commit -m 'Update SRI hash for main.js'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
