name: Update SRI Hash

on:
  push:
    branches:
      - develop
    paths:
      - 'main.js'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-sri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SRI hash using openssl and update HTML
        run: |
          # Generate the sha256 SRI hash using openssl
          HASH=$(openssl dgst -sha256 -binary main.js | openssl base64 -A)
          
          # Update HTML file with the new integrity hash
          sed -i "s|<script src=\"main.js\".*>|<script src=\"main.js\" integrity=\"sha256-$HASH\" crossorigin=\"anonymous\"></script>|" index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Update SRI hash for main.js'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
