name: Update SRI Hash

on:
  # Trigger on any push to any branch
  push:
    paths:
      - 'src/proj/main.js'  # Run whenever main.js changes

  # Allow manual triggering of the action
  workflow_dispatch:

jobs:
  update-sri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip  # No additional dependencies needed for this script

      - name: Run SRI Update Python Script
        run: python scripts/update_sri.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/proj/index.html
          git commit -m 'Update SRI hash for main.js'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
